# Site settings
title: I AM DINGLINXIAO
email: dlx1986@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  总结/积累/沉淀
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dinglx
github_username:  dinglx

# Build settings
markdown: kramdown
